POST https://notes-backend-170-559917148272.us-central1.run.app/register
Content-Type: application/json

{
    "username": "Malik",
    "password": "ikan",
    "confirm_password": "ikan"
}

###
POST https://notes-backend-170-559917148272.us-central1.run.app/login
Content-Type: application/json

{
    "username": "Malik",
    "password": "ikan"
}

###
GET http://localhost:5000/token

###
GET http://localhost:5000/notes
Content-Type: application/json
Authorization: Bereer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJNYWxpayIsImlhdCI6MTc0ODI2MDgyNiwiZXhwIjoxNzQ4MjYwODU2fQ.XJQbVO6VHxk1bVufRfmbdxA0IUDi4tuMCEIDyQI9j80

{
  "title": "Test Ubah",
  "content": "Ini"
}